apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind:  Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 4 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: schordingermiao/ass1:0123
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 1024
        - containerPort: 5000
       
